-- INNER(NATURAL) JOIN
select * from REGIONS natural join COUNTRIES;


-- JOIN USING
select FIRST_NAME, LAST_NAME, jh.JOB_ID, START_DATE, END_DATE
from EMPLOYEES join JOB_HISTORY jh using (EMPLOYEE_ID, DEPARTMENT_ID);

-- JOIN ON
select FIRST_NAME, LAST_NAME, jh.JOB_ID, START_DATE, END_DATE
from EMPLOYEES join JOB_HISTORY jh on (EMPLOYEES.EMPLOYEE_ID = jh.EMPLOYEE_ID);